# Generated by Django 4.1 on 2022-08-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Super',
            new_name='Supers',
        ),
    ]
