# Generated by Django 4.1 on 2022-08-31 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0005_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
